name: BENCHMARK_BENCHER
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  benchmark_base_branch:
    name: Continuous Benchmarking with Bencher
    permissions:
      checks: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: bencherdev/bencher@main
      - name: Run macro benchmarks
        run: make macrobenchmark
      - name: Track base branch macro benchmarks with Bencher
        run: |
          bencher run \
          --project ip-week-poc \
          --token '${{ secrets.BENCHER_API_TOKEN }}' \
          --branch main \
          --testbed ubuntu-latest \
          --threshold-measure latency \
          --threshold-test percentage \
          --threshold-max-sample-size 64 \
          --threshold-upper-boundary 2 \
          --threshold-lower-boundary 2 \
          --thresholds-reset \
          --err \
          --github-actions '${{ secrets.GITHUB_TOKEN }}' \
          --file macrobenchmark_results.json
