name: BENCHMARK_BENCHER
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  benchmark_base_branch:
    name: Continuous Benchmarking with Bencher
    permissions:
      checks: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: bencherdev/bencher@main
      - name: Compile benchmark
        run: g++ benchmark_game.cpp play_game.cpp -std=c++11 -isystem include/ -L. -lbenchmark -lpthread -o mybenchmark
      - name: Create benchmark result json
        run: ./mybenchmark --benchmark_out_format=json --benchmark_out=results.json
      - name: Track base branch benchmarks with Bencher
        run: |
          bencher run \
          --project thibaut-lermytte-s-project \
          --token '${{ secrets.BENCHER_API_TOKEN }}' \
          --branch main \
          --testbed ubuntu-latest \
          --threshold-measure latency \
          --threshold-test t_test \
          --threshold-max-sample-size 64 \
          --threshold-upper-boundary 0.99 \
          --thresholds-reset \
          --err \
          --github-actions '${{ secrets.GITHUB_TOKEN }}' \
          --file results.json
